image: golang:1.22.4

stages:
  - test
  - build
  # - deploy

variables:
  GOLANGCI_LINT_VERSION: 'v1.59.1'
lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: test
  script:
    - golangci-lint run --print-issued-lines=false

go-test:
    stage: test
    script:
      - go test -v -coverpkg=./... -coverprofile=coverage.txt ./...
      - go install github.com/t-yuki/gocover-cobertura@latest
      - gocover-cobertura < coverage.txt > coverage.xml
      - ls -l
    coverage: '/coverage: \d+.\d+% of statements/'
    artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml
        
build:
  stage: build
  script:
    - go build -o iam cmd/iam/main.go