image: golang:1.22.4

stages:
  - test
  - build
  # - deploy

variables:
  GOLANGCI_LINT_VERSION: 'v1.59.1'
lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: test
  script:
    - golangci-lint run --print-issued-lines=false

go-test:
    stage: test
    script:
      - go test -coverprofile=coverage.out ./...
      - ls -l
    artifacts:
      paths:
        - coverage.out
        
build:
  stage: build
  script:
    - go build -o iam cmd/iam/main.go