image: golang:1.22.4-alpine3.20

stages:
  - test
  - build
  # - deploy

variables:
  GOLANGCI_LINT_VERSION: 'v1.59.1'
lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: test
  script:
    # Write the code coverage report to gl-code-quality-report.json
    # and print linting issues to stdout in the format: path/to/file:line description
    - golangci-lint run --print-issued-lines=false --out-format code-climate:gl-code-quality-report.json,line-number
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

go-test:
    stage: test
    script:
      - go get github.com/t-yuki/gocover-cobertura
      - go test  ./... -v -coverprofile coverage.txt
      - gocover-cobertura < coverage.txt > coverage.xml
    coverage: /^coverage:\s(\d+(?:\.\d+)?%)/
    artifacts:
      name: $CI_JOB_NAME/coverage.txt
      paths:
        - coverage.xml
      expire_in: 2 days
      reports:
        cobertura: coverage.xml

build:
  stage: build
  script:
    - go build -o iam cmd/iam/main.go
  artifacts:
    paths:
      - iam