# Options for analysis running.
run:
  concurrency: 4
  timeout: 5m
  tests: true
  issues-exit-code: 1
output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true
  sort-order: severity
  show-stats: true
linters-settings:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unsed
    - revive
linters:
  revive:
    ignoreGeneratedHeader: false
    severity: warning
    confidence: 0.8
    errorCode: 0
    warningCode: 0
issues:
  option: value
severity:
  default-severity: warning
  case-sensitive: true