services:
  iam:
    container_name: iam
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    volumes: 
      - ../.:/app
    ports:
      - "3000:3000"
    depends_on:
      - db-iam
    networks:
      - project-v
  db-iam:
    container_name: db-iam
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - project-v

volumes:
  postgres:

networks:
  project-v:
    external: true